ehsan@sandbox ~ % sudo adduser --system --shell /bin/bash --gecos 'Git SCM' --group --disabled-password git
Adding system user `git' (UID 106) ...
Adding new group `git' (GID 112) ...
Adding new user `git' (UID 106) with group `git' ...
Creating home directory `/home/git' ...
