CREATE USER 'dashboard'@'%' IDENTIFIED BY 'dashboard';

GRANT USAGE ON * . * TO 'dashboard'@'%' IDENTIFIED BY 'dashboard' WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

CREATE DATABASE IF NOT EXISTS `dashboard` ;

GRANT ALL PRIVILEGES ON `dashboard` . * TO 'dashboard'@'%';
